In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = np.random.randint(0,100,(10,2))

In [5]:
data

array([[95, 23],
       [90, 89],
       [75,  7],
       [55, 25],
       [64, 59],
       [32, 77],
       [74,  7],
       [53, 90],
       [31, 76],
       [31, 77]])

In [6]:
scaler_model = MinMaxScaler()

In [7]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [8]:
scaler_model.fit(data)

/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [9]:
scaler_model.transform(data)

array([[ 1.        ,  0.19277108],
       [ 0.921875  ,  0.98795181],
       [ 0.6875    ,  0.        ],
       [ 0.375     ,  0.21686747],
       [ 0.515625  ,  0.62650602],
       [ 0.015625  ,  0.84337349],
       [ 0.671875  ,  0.        ],
       [ 0.34375   ,  1.        ],
       [ 0.        ,  0.8313253 ],
       [ 0.        ,  0.84337349]])

In [10]:
scaler_model.fit_transform(data)

/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 1.        ,  0.19277108],
       [ 0.921875  ,  0.98795181],
       [ 0.6875    ,  0.        ],
       [ 0.375     ,  0.21686747],
       [ 0.515625  ,  0.62650602],
       [ 0.015625  ,  0.84337349],
       [ 0.671875  ,  0.        ],
       [ 0.34375   ,  1.        ],
       [ 0.        ,  0.8313253 ],
       [ 0.        ,  0.84337349]])